server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: qingyu-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qingyu_picture
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 是否开启自动驼峰命名规则（默认false）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 设置MyBatis日志实现类，这里配置为控制台输出
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段名称
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
#      接口文档配置
knife4j:
  enable: true
  openapi:
    title: Knife4j接口文档
    description: "智能云协同图库"
    email: liqingyu.dev@foxmail.com
    version: v4.0
    group:
      test1:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.qingyu.qingyupicturebackend.controller
#腾讯云对象存储
#cos:
#  client:
#    secretId: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx